### ISSUE TITLE
work perfect!!! 

### ISSUE THREAD

**Issue by guyyar89** [lolouk44/xiaomi_mi_scale#10]
i dont know how to send you massage but maybe you can build integration same for Xiaomi Mi Scale?

**Comment by lolouk44** [comment]
Which scale do you have, can you send me a picture?
What happens when you try to run my app? Do you get any data? What do you see in the logs?

**Comment by lukich48** [comment]
I have Xiaomi Mi Weight Scale 2 XMTZC04HM. How do you think it will work? It sends only weight value
https://www.amazon.co.uk/Xiaomi-Bathroom-High-Precision-Accuracy-Calculator/dp/B07VLN38BL/ref=pd_sbs_364_2/257-5709726-8381330?_encoding=UTF8&pd_rd_i=B07VLN38BL&pd_rd_r=0a63439c-98f1-4e2d-9b07-d39868072ca5&pd_rd_w=aHYCH&pd_rd_wg=Iixy3&pf_rd_p=2773aa8e-42c5-4dbe-bda8-5cdf226aa078&pf_rd_r=HRPXHHJGEZRXSZZYRMJP&psc=1&refRID=HRPXHHJGEZRXSZZYRMJP

**Comment by lolouk44** [comment]
@lukich48 it doesn't look like your scale has Bluetooth?
If so the script can't communicate with the scale and can't retrieve measures....

**Comment by lukich48** [comment]
@lolouk44 No, it has bluetooth. I receive values of weight in Mi Fit through bluetooth . 
Perhaps I should just try your script... maybe later )
