### ISSUE TITLE
Not working on Raspberry Pi3

### ISSUE THREAD

**Issue by lolouk44** [lolouk44/xiaomi_mi_scale#11]
Getting this on fresh Raspberry Pi 3 install:
```
MQTT connection: Connection Accepted.
Traceback (most recent call last):
  File "/opt/miscale/Xiaomi_Scale.py", line 180, in <module>
    main()
  File "/opt/miscale/Xiaomi_Scale.py", line 173, in main
    scanner.scan(5)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 797, in start
    self._mgmtCmd(self._cmd()+"end")
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'scanend' (code: 11, error: Rejected)
```

**Comment by lolouk44** [comment]
To be investigated if this occurs because the scale is sleeping or there is an issue with the BT connection.
Issue not experienced on Desktop computer with Ubuntu 16.04
Users have reported that using a BT dongle fixes it.

**Comment by lolouk44** [comment]
possibly related to https://github.com/lolouk44/xiaomi_mi_scale/issues/12

**Comment by grantcodes** [comment]
Just confirming I'm also seeing this on a pi 3. Just pulled an update right now though so I'll see how that goes

**Comment by lolouk44** [comment]
Thanks. The Bluetooth comms really need to be rebuilt from scratch as they're far for efficient. No idea when il ne able to crack this up though as this was my first foray into the Bluetooth world.

**Comment by grantcodes** [comment]
Not had any issues since the last update though! Been running constantly since then without issue :D

**Comment by lolouk44** [comment]
That's great, thanks. I'll close this issue for now, though I suspect it's not fully resolved, but this is due to bluepy that has issues and doesn't appear to be maintained anymore...
