### ISSUE TITLE
Stopped working after latest update

### ISSUE THREAD

**Issue by jihonrado** [lolouk44/xiaomi_mi_scale#13]
Hi,

First of all, thanks @lolouk44 for this integration. I have been using it for around two months.

Yesterday, I upgraded to the latest version and it stopped working (it does not send the data to MQTT). The following log traces appear continuously:

```
mi-scale            | Error while running the script, continuing. If you see this message too often/constantly there is probably a real issue...
mi-scale            | Error while running the script, continuing. If you see this message too often/constantly there is probably a real issue...
mi-scale            | Error while running the script, continuing. If you see this message too often/constantly there is probably a real issue...
mi-scale            | Error while running the script, continuing. If you see this message too often/constantly there is probably a real issue...
mi-scale            | Error while running the script, continuing. If you see this message too often/constantly there is probably a real issue...
```
Details about my setup:

- `xiaomi_mi_scale` running with docker-compose using `network_mode: host` and `privileged: true`.
- Running within a Intel NUC using its built-in bluetooth.
- The bluetooth is working properly as I am able to use it from other services.
- I also tested using a bluetooth dongle with the same result.
- It was working fine until I pulled the latest container version.

Could it be related to the [passive scanning](https://github.com/lolouk44/xiaomi_mi_scale/blob/42f3aa4426d13fa6a5ea230cc617b5555ae55373/src/Xiaomi_Scale.py#L176)? :thinking:

**Comment by lolouk44** [comment]
added this to logging. it would probably have failed before but did not log it
there were no other changes to the code, so if it worked before it would work the same now.
I am aware the code is a bit flaky and I'll look at it again when I get some time

**Comment by jihonrado** [comment]
Hi @lolouk44, thanks for your reply. I did not have time yet to perform proper debugging on this (building old versions images manually), I will let you know. I was just able to verify that the setup is the same than before (as far as I know) and both the Bluetooth module and the scale work properly (it reports correctly to Xiaomi app). I'll keep you posted.
