### ISSUE TITLE
disconnected from mqtt

### ISSUE THREAD

**Issue by bpaulin** [lolouk44/xiaomi_mi_scale#16]
hello,

this may be related to #2 ... or maybe not
mqtt client sometimes disconnects from mqtt, and fails to publish the next payload.

I'm wondering if we really need to have to have a always connected client? I'd rather use https://pypi.org/project/paho-mqtt/#single to connect-publish-disconnect each time we receive a payload from the scale, it works like that in my setup.

What do you think? are you interested in a PR to change that?

thanks for your work!

**Comment by lolouk44** [comment]
Thanks, that makes sense. Happy with a PR or I can work on it myself. I anyway need to rebuild the container with your earlier changes, which I'll do tonight...

**Comment by bpaulin** [comment]
I'll work on a clean PR about that, thanks
