### ISSUE TITLE
Doesn't run script

### ISSUE THREAD

**Issue by msslava** [lolouk44/xiaomi_mi_scale#18]
Hi, 

The last update does not run the script.

`~/xiaomi_mi_scale/src $ python3 Xiaomi_Scale.py
  File "Xiaomi_Scale.py", line 146
    sys.stdout.write(f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')} - Publishing data to topic {MQTT_PREFIX + '/' + user + '/weight'}: {message}\n")
                                                                                                                                                    ^
SyntaxError: invalid syntax`

My environment:
raspberry pi 2
bluetooth stick

**Comment by bpaulin** [comment]
Hello,

Syntax error may come from a wrong python version, can you send ```python --version``` ?

**Comment by msslava** [comment]
Hello, 
Sorry for the late reply,
I have Python 2.7.13  installed

**Comment by lolouk44** [comment]
you need python3 to run the script.
if you run the script manually, make sure you call it with python3 (like you did above):
Try and run it un-buffered (with `-u`):
`python3 -u Xiaomi_Scale.py`

**Comment by msslava** [comment]
Same error:

`
pi@server:~/xiaomi_mi_scale/src $ python3 -u Xiaomi_Scale.py
  File "Xiaomi_Scale.py", line 146
    sys.stdout.write(f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')} - Publishing data to topic {MQTT_PREFIX + '/' + user + '/weight'}: {message}\n")
                                                                                                                                                    ^
SyntaxError: invalid syntax
`

**Comment by lolouk44** [comment]
which version of python3 do you have?
(`python3 --version`)
The only thing I can think of i the f-strings which need python 3.6 or higher
Any reason you're not using the docker container? All pre-requisites are installed for you...

**Comment by msslava** [comment]
Python 3.5.3.

I do not use docker, because the raspberry does not have enough performance. The containers stop after a while.
All pre-requisites are installed.

**Comment by lolouk44** [comment]
ok, then you need to upgrade to python 3.6 or higher...
Alternatively feel free to update the `sys.stdout.write` lines that include f-strings (starting f") and replace them with the "old" style as you see fit...

**Comment by msslava** [comment]
Ok, thank you
