### ISSUE TITLE
Make used Bluetooth Device configurable

### ISSUE THREAD

**Issue by stefangries** [lolouk44/xiaomi_mi_scale#19]
The software picks hci0 as default bluetooth device to communicate with the scale. It would be great, if it would be configurable as docker environment variable, which hci device the software uses. This would make it possible to use the bluetooth device nearest to the scale or the device with the highest range.

**Comment by lolouk44** [comment]
Can you try this branch and let me know if that works for you?
https://github.com/lolouk44/xiaomi_mi_scale/tree/0.1.4b-hci-selector

**Comment by lolouk44** [comment]
also pushed docker image 0.1.4b if you prefer...

**Comment by stefangries** [comment]
I built the image myself now, it works! But is it possible that there is still a change to be made here?
https://github.com/lolouk44/xiaomi_mi_scale/blob/0.1.4b-hci-selector/src/Xiaomi_Scale.py#L178

Btw, on my XMTZC05HM, I only get the following values:
Weight, BMI, Basal Metabolism, Visceral Fat, TimeStamp.

Is that correct? Shouldn't there be the other values like in the following image, too?
https://github.com/lolouk44/xiaomi_mi_scale/blob/master/Screenshots/HA_Lovelace_Card_Details.png

But the most important thing: Thank you very much for the work!

**Comment by stefangries** [comment]
Update: The values are there now. Seems like, they just needed a few minutes to arrive.

**Comment by lolouk44** [comment]
Great stuff. I'll merge the branches and push an official image on docker later
