### ISSUE TITLE
Bluetooth device name does not contain the word "MIBCS"

### ISSUE THREAD

**Issue by Welcius** [lolouk44/xiaomi_mi_scale#20]
Hello! I just installed and tested the connector with my scale, thank you so much, works flawlessly!
That being said, I wanted to mention that during the configuration I did not find any device with this command:

`$ sudo hcitool lescan | grep -i MIBCS`

After checking, I did see that the device name was `MI SCALE2`, so maybe that could be added to that grep command as well :)

Here's some data from my scale:

> Product name: Mi Smart Scale 2
> Bluetooth device name: MI SCALE2
> Bluetooth address: C8:47:8C:BA:CB:XX
> Model: XMTZC04HM
> Firmware version: 1.0.0.12

**Comment by lolouk44** [comment]
Thanks, updated the readme file
