### ISSUE TITLE
Does xiaomi_mi_scale use the Rpi's built in bluetooth or does it require a dongle

### ISSUE THREAD

**Issue by JeffCdev** [lolouk44/xiaomi_mi_scale#21]
Hi lolouk44, really interested in giving your app a go, but want to make sure I know what's required.  I have  Rpi3, but don't have a bluetooth dongle.  I've had several issues with bluetooth on my RPi (for example, I can't get OSMC to use the internal bluetooth to connect to headphones) and just wanted to double-check before getting started.
Thanks!!!

**Comment by lolouk44** [comment]
Hi @JeffCdev, You can use the built in bluetooth but there are several reports of it being unstable so I would suggest a BT dongle...
