### ISSUE TITLE
Remove "network_mode=host" from Docker example

### ISSUE THREAD

**Issue by ualex73** [lolouk44/xiaomi_mi_scale#26]
**Is your feature request related to a problem? Please describe.**
The docker-compose example contains "network_mode=host", which is not needed and it is bad practice to do this (less secure).

**Describe the solution you'd like**
Remove "network_mode=host" from example

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lolouk44** [comment]
Thanks for your feedback. I found out that it doesn't work for me if I don't set `network_mode: host`
I get this:

![image](https://user-images.githubusercontent.com/4587746/86589680-047c4f80-bf86-11ea-8633-10d462c3daa9.png)
Remember that bluetooth is part of the "network"...

**Comment by ualex73** [comment]
Aha, i see it now. The MQTT fails silently (hangs) on my side, then it never hits that part of the code :-(

**Comment by lolouk44** [comment]
No worries. Glad it's sorted :)

**Comment by ualex73** [comment]
Np, i will re-write the MQTT code myself, because it is not very ideal to use publish single (i prefer a connection to be open and keepalives to be happening). This then will solve also this problem with discovery.

**Comment by lolouk44** [comment]
Thanks. I expressly changed the code to not keep the connection open since it's not truly required: it's only a one off message sent once in a while (typically once a day per person).
See discussion [here](https://github.com/lolouk44/xiaomi_mi_scale/issues/16)
But feel free to fork out :)

**Comment by ualex73** [comment]
I know it low number of messages, but if the connection is open ... i know everything is up-and-running on all ends (i monitor all my connections to/from my MQTT broker and send a Telegram if things go wrong ;-)).
