### ISSUE TITLE
Script for data processing

### ISSUE THREAD

**Issue by RobertWojtowicz** [lolouk44/xiaomi_mi_scale#27]
Hi,

Based on this project https://github.com/rando-calrissian/esp32_xiaomi_mi_2_hass I modified the code for ESP32 and read scale data to a file (bash script). The format is as follows:
Weight,Impedance,Units,User,Timestamp
58.15,5.45,kg,7,1594556443,5

I would like to ask you to modify the python script (Xiaomi_Scale.py ?) to get the data file:
"Bone" (bone mass in percent),
"Fat" (fat in percent),
"Hydration" (hydration in percent),
"metabolicAge",
"muscle" (muscle mass in percent),
"visceralFat" (visceral fat rating (valid values: 1-60)),
"weight" (weight in kilograms),
"physiqueRating" (physique rating (valid values: 1-9))
"Timestamp" it ok unix-timestamp

It's all about creating a Xiaomi Scale synchronization to Garmin Connect with this project: https://github.com/davidkroell/bodycomposition

I know that maybe too many wishes, but maybe it is not difficult for you, I will be grateful for your help. I am not a programmer, I try to stick several projects together :)

Of course, when everything works, I will want to put it on github :)

Best Regards,
Robert

**Comment by lolouk44** [comment]
I'm not familiar with the other projects so unlikely I would do this. Just a quick question though, why don't you subscribe to the MQTT broker/topic to retrieve the data from there and then generate your file?

**Comment by RobertWojtowicz** [comment]
Subscribes to a broker, only without Home Assistant Bridge. This is the resulting script that generates the described file format:
`#!/bin/bash

#data acquisition
user=admin
passwd=[assowrd]
host=mi
export_file=data.log

#create file with data
mosquitto_sub -h $host -t "data" -u $user -P $passwd -C 1 > $export_file
sed -i 's/$/,'$physiqueRating'/;1iWeight,Impedance,Units,User,Timestamp' $export_file
sed -Ei '2,$ s/(([^,]*,){4})([^,]+)(.*)/echo \x27\1\x27$(date -d "\3" +%s)\x27\4\x27/e' $export_file`

I would like to process this data somehow as I wrote above.

**Comment by lolouk44** [comment]
I'm sorry I'm not really good a bashing. Sounds like you got the right idea with mosquitto_sub.
You however set `-C 1` so your bash script will stop after receiving 1 message
Sorry I can't help you any further.
