### ISSUE TITLE
Better timestamp format

### ISSUE THREAD

**Issue by vassilis-panos** [lolouk44/xiaomi_mi_scale#29]
Is it possible to send the timestamp in the following format?
2020-09-07T10:46:40.867941+00:00

The current timestamp string is not useful in HA and the front-end is unable to treat this value as date.
Thank you.

**Comment by lolouk44** [comment]
I can look into it
This attribute was originally there as a visual check to ensure that the data sent was refreshed.
Why not use the sensor's last_changed or last_updated attribute, which should be more or less the same except maybe a couple of seconds late if your MQTT broker is REALLY busy?

**Comment by vassilis-panos** [comment]
Because last_changed and last_updated are reset after restarting HA. The timestamp is always retained in the MQTT message and can be revoked after restarting HA

**Comment by lolouk44** [comment]
Got it. Let me look into it

**Comment by lolouk44** [comment]
Fixed in 0.1.8, though I'm using the standard python output without custom format.

**Comment by lolouk44** [comment]
Reopening as I just realised I had only tested and not implemented this.
Changed the code for the next release from `datetime.today().strftime('%Y-%m-%d-%H:%M:%S')` to `datetime.now()`

**Comment by lolouk44** [comment]
Fixed in [0.1.11](https://github.com/lolouk44/xiaomi_mi_scale/releases/tag/0.1.11)
