### ISSUE TITLE
need json config file , but cannot find this from source code.

### ISSUE THREAD

**Issue by 5high** [lolouk44/xiaomi_mi_scale#32]
**Describe the bug**
I am follow script directly running guide

<pre>Running script directly on your host system (if your platform is not listed/supported):
Note: Python 3.6 or higher is required to run the script manually

Install python requirements (pip3 install -r requirements.txt)
Open wrapper.sh and configure your environment variables to suit your setup.
Add a cron-tab entry to wrapper like so:
@reboot bash /path/to/wrapper.sh
NOTE: Although once started the script runs continuously, it may take a few seconds for the data to be retrieved, computed and sent via mqtt.</pre>
**To Reproduce**
Steps to reproduce the behaviour, including error message if any.

**Expected behaviour**

run the shell show me error , cannot find json file ,but I can't find out sample json file.

<pre>
-------------------------------------
2020-09-29 21:48:20 - Starting Xiaomi mi Scale...
2020-09-29 21:48:20 - Loading Config From OS Environment...
Traceback (most recent call last):
  File "/root/xiaomi_mi_scale/src/Xiaomi_Scale.py", line 28, in <module>
    with open('/data/options.json') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/data/options.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/xiaomi_mi_scale/src/Xiaomi_Scale.py", line 165, in <module>
    if MQTT_DISCOVERY.lower() in ['true', '1', 'y', 'yes']:
AttributeError: 'bool' object has no attribute 'lower'
</pre>

**Screenshots**

**Scale (please complete the following information):**
 - Name
 - Model #

**Desktop/Server (please complete the following information):**
 - manually ran after a Git Clone , running on aarch64.

**Additional context**

**Comment by lolouk44** [comment]
Please provide the details requested in the issue form if you need help
Also confirm which version of the container you're using

**Comment by 5high** [comment]
Thank you for your reply , I am edited issue content.

**Comment by lolouk44** [comment]
What type of computer are you running the script on please?
Which version of Python3 do you have installed?

**Comment by 5high** [comment]
I am using ArmBian aarch64
Python3.7.3

**Comment by lolouk44** [comment]
I don't understand why this fails for you, unless you're using an old version of the code?
Can you try and delete the local copy and re-clone / re-pull the repo?

**Comment by Proxx** [comment]
the problem is using the docker-compose example.

comment out the empty values
`    environment:
    - HCI_DEV=hci0                  # Bluetooth hci device to use. Defaults to hci0
    - MISCALE_MAC=00:00:00:00:00:00 # Mac address of your scale
    - MQTT_HOST=127.0.0.1           # MQTT Server (defaults to 127.0.0.1)
    - MQTT_PREFIX=miscale           # MQTT Topic Prefix. Defaults to miscale
#    - MQTT_USERNAME=                # Username for MQTT server (comment out if not required)
#    - MQTT_PASSWORD=                # Password for MQTT (comment out if not required)
#    - MQTT_PORT=                    # Defaults to 1883
    - TIME_INTERVAL=30              # Time in sec between each query to the scale, to allow other applications to use the Bluetooth module. Defaults to 30
    - MQTT_DISCOVERY=true           # Home Assistant Discovery (true/false), defaults to true
#    - MQTT_DISCOVERY_PREFIX=        # Home Assistant Discovery Prefix, defaults to homeassistant
`

at least that solved my problems

**Comment by lolouk44** [comment]
Thanks for the update.
Indeed values need to be provided in docker-compose environment variables if they are listed. If you do not need these, you need to comment them out.
