### ISSUE TITLE
discovery messages use miscale as MQTT_PREFIX

### ISSUE THREAD

**Issue by Sk4zz** [lolouk44/xiaomi_mi_scale#35]
I have changed the MQTT_PREFIX in my docker-compose.yaml and was wondering why the discovery message still hat the miscale prefix. 
I just realized that the discovery function in Xiaomi_Scale.py uses miscale as hardcoded prefix instead of the environment variable.

**Comment by lolouk44** [comment]
Thanks. I've updated the code for the next version.

**Comment by lolouk44** [comment]
Fixed in https://github.com/lolouk44/xiaomi_mi_scale/releases/tag/0.1.11
