### ISSUE TITLE
Issues with Mi Body Composition Scale 2

### ISSUE THREAD

**Issue by lerra** [lolouk44/xiaomi_mi_scale#38]
**Describe the bug**
Can't get the Mi Body Composition Scale 2 to be discovered. I have paired with the mi fit app and the scale work. When I exec into the container (docker exec -it $dockerId bash) I can confirm that bluetooth works (getting output from hcitool -i hci0 scan and blescan, tried to grep on the mac addr from the app but could not be found). I am also running latest docker container and I can confirm the export vars are set inside in the container from the docker-compose.yml

**Expected behaviour**
I expect to get some output (I guess?) from docker logs -f and data to mqtt (confirmed connectivity and credentials) and I can't see such with sub to the mqtt topic.

**Scale (please complete the following information):**
 - Name Mi Body Composition Scale 2 
 - Model #XMTZC05HM
 - Firmware 1.0.0.12

**Desktop/Server (please complete the following information):**
- Docker
- NUC
- Built in

**Additional context**
It's the first time I am trying this project so it have never been working and I also just go the scale (confirmed to work in the mi fit app).

**Comment by lolouk44** [comment]
Make sure you kill the mi app before you try else it'll lock the connection to the scale. 
Of that's t your issue can you please acknowledge and close this issue?

**Comment by lerra** [comment]
Sorry, forgot to mention that but after pairing and getting the BT mac address I have been unpairing it. I also confirmed that now so it is still an issue :(

**Comment by lolouk44** [comment]
if you get something via blescan, then the BT is working indeed. If you're not getting the MAC of the scale:
1) make sure the scale is close enough to the BT dongle
2) step on the scale to wake it up and try again (the scale goes to sleep within ~10 min and won't answer to pings

**Comment by lerra** [comment]
Hi mate, you got spot on on the physical part on point one that i under estimated. It started to work when I took up the scale 0.3m up from the floor (3-4m from the nuc)...now I need to looking into find a external usb dongle. Big thanks
