### ISSUE TITLE
wrapper.sh is missing whole section on mqtt configuration

### ISSUE THREAD

**Issue by saikek** [lolouk44/xiaomi_mi_scale#40]
**Describe the bug**
wrapper.sh is missing whole section on mqtt configuration.

**To Reproduce**
compare contents of wrapper.sh with docker-compose

**Expected behaviour**
It should be equals

**Screenshots**

**Desktop/Server (please complete the following information):**
 - Python 3.9, venv

**Comment by lolouk44** [comment]
Thanks. Most people use the docker version so not looked at the wrapper in ages. I'll update shortly

**Comment by lolouk44** [comment]
done
