### ISSUE TITLE
Why retain scale data?

### ISSUE THREAD

**Issue by andreasbrett** [lolouk44/xiaomi_mi_scale#44]
Is there a reason for retaining the scale data? I understand why retaining the discovery messages is a must but scale measurements should not need to be retained as Home Assistant should pick them up and then they're not needed anymore.

https://github.com/lolouk44/xiaomi_mi_scale/blob/a5ddd5d334fd1968baabd510ef93d47484d31fbb/src/Xiaomi_Scale.py#L303

**Comment by lolouk44** [comment]
Hi @andreasbrett 

I agree in principle with your comment, however not all users of this repo use HA, that's why I'm publishing with the retain flag.
Did you have any concern with leaving it on?

**Comment by andreasbrett** [comment]
No, no big concerns. I just don't like the idea of my family's personal data dangling on the MQTT server. Maybe I'm just paranoid to be honest... I much prefer the send-and-forget approach. Also I heard the HA devs talking about how retained MQTT messages are a pain (not sure why though). How about making this an option defaulting to retain=True?

**Comment by lolouk44** [comment]
> How about making this an option defaulting to retain=True?

That's a good idea. I'll add this on top of your PR
