### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by xMrVizzy** [lolouk44/xiaomi_mi_scale#5]
Docker logs!
<img width="619" alt="CleanShot 2019-11-26 at 04 44 28@2x" src="https://user-images.githubusercontent.com/7906418/69587472-76abaf80-1007-11ea-8d72-7501f0c163f0.png">

Enviroments
![CleanShot 2019-11-26 at 04 45 16@2x](https://user-images.githubusercontent.com/7906418/69587570-b6729700-1007-11ea-89ad-77679c16d7b6.png)

**Comment by xMrVizzy** [comment]
I run on Raspberry Pi 4

**Comment by lolouk44** [comment]
sorry not had any chance / time to look into this in more details. All I can say is that this may happen if your scale is sleeping. Doesn't impact functionality.
Just make sure also that you've set your environment entries correctly in the docker-compose file

**Comment by xMrVizzy** [comment]
![098E8D39-6C97-4F75-9072-4E74738ADF30](https://user-images.githubusercontent.com/7906418/70669640-c1c8f200-1c98-11ea-8358-f751306f90ee.png)

I check using app that measurement is work, and it mean that scale not sleep, but same error in console of Docker Container!

**Comment by xMrVizzy** [comment]
![DA726348-0C27-496C-8846-BEDB961185C6](https://user-images.githubusercontent.com/7906418/70669810-4156c100-1c99-11ea-9813-e328b471dcba.png)

This is my docker-compose file, I made a measurement with Mi Fit app, and its mean that scales not sleep, and after that I checked MQTT topics, and there no miScale topic, and also same error in console!

**Comment by lolouk44** [comment]
Stupid question, were you using the MiFit app every time you tested? I'm not sure the scale accepts multiple simultaneous bluetooth connections...
With the mifit app not running/killed, start the container.
Step on the scale and get a reading. It should then show up on mqtt.
Also how do you check your MQTT topic?
Last but not least: I don't have a Pi4 to test, have you tried on a different device/architecture (in case it's purely a Pi4 architecture issue)

**Comment by xMrVizzy** [comment]
No I tried only once with Mi Fit running, the other times were without the app!

**Comment by lolouk44** [comment]
Thanks. If you could test on your Pi3. For Pi1 and Pi3 I actually built the docker container on the RPI itself, but for Pi4 I used docker desktop on Windows which was supposed to allow cross platform build...

**Comment by jwhite** [comment]
I'm getting the same failure here on a RPi3.

Interestingly the test script works fine.

![image](https://user-images.githubusercontent.com/473577/71636653-d9900680-2c97-11ea-866a-ee72f9df22f8.png)

**Comment by lolouk44** [comment]
That error message occurs if there's an issue with the impedance reading. Doesn't stop the script from running. If you step on the scale barre feet the error should not show up. I need to add a catch so it doesn't look like it fails.
