### ISSUE TITLE
Add Weight Guru scale ( BT )

### ISSUE THREAD

**Issue by Vendo232** [lolouk44/xiaomi_mi_scale#52]
**Is your feature request related to a problem? Please describe.**

Would be able to add Weight Guru Scale which also sends data via BT after measurement is complete?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lolouk44** [comment]
Sorry the Weight Guru Scales are a different brand / ecosystem and as such would be using different communication methods via Bluetooth.
It's not something that can therfore simply be added.
