### ISSUE TITLE
Warning in supervisor log

### ISSUE THREAD

**Issue by raidnet-ms** [lolouk44/xiaomi_mi_scale#56]
**Describe the bug**
I get the following warning in the supervisor log:

WARNING (MainThread) [supervisor.addons.options] Option 'TIME_INTERVAL' does not exist in the schema for Xiaomi Mi Scale (xiaomi_mi_scale)

**To Reproduce**
Go in supervisor log and check errors

**Expected behaviour**
No warnings

**Screenshots**

**Scale (please complete the following information):**
 - Name
 Xiaomi Mi Body Composition Scale 2
 - Model #
 XMTZC05HM

**Desktop/Server (please complete the following information):**
 - Docker or manually ran after a Git Clone?
 Added the repository to HA os
 - Device used to run the Script/Container [e.g. Raspberry Pi, NUC]
 Raspberry with HA Os
 - Bluetooth device used [e.g. Built-in, USB Dongle]
 Builtin rasp BT

**Additional context**

**Comment by lolouk44** [comment]
Thanks. As per the message you need to remove the `TIME_INTERVAL` option from your add-on config.

**Comment by raidnet-ms** [comment]
Oh thanks, it was hidden in the yaml view (of course the value is not supported in the UI form) so i didn't notice.
