### ISSUE TITLE
Mi Scale 1 issue

### ISSUE THREAD

**Issue by InsaneGriever** [lolouk44/xiaomi_mi_scale#8]
```
  File "/opt/miscale/Xiaomi_Scale.py", line 181, in <module>,
Traceback (most recent call last):,
    main(),
  File "/opt/miscale/Xiaomi_Scale.py", line 174, in main,
    scanner.scan(5),
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 853, in scan,
    self.process(timeout),
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 842, in process,
    self.delegate.handleDiscovery(dev, (dev.updateCount <= 1), isNewData),
  File "/opt/miscale/Xiaomi_Scale.py", line 87, in handleDiscovery,
    self._publish(round(measured, 2), unit, 0, "", ""),
  File "/opt/miscale/Xiaomi_Scale.py", line 161, in _publish,
    message += ',"TimeStamp":"' + mitdatetime + '"',
TypeError: can only concatenate str (not "int") to str
```
Mi Scale 1
Thanks in advance.

**Comment by lolouk44** [comment]
Please try and download the latest code / container that was pushed yesterday as it includes a fix for this

**Comment by InsaneGriever** [comment]
This is after last fix.

**Comment by lolouk44** [comment]
> `self._publish(round(measured, 2), unit, 0, "", ""),`

This tells me you're still somehow on an older version.

Code on latest commit is now:
`self._publish(round(measured, 2), unit, str(datetime.today().strftime('%Y-%m-%d-%H:%M:%S')), "", "")`

What is the date of your image? Should be 3rd Feb.
Try and force delete your image and then download it again.
I've had a similar issue in that pulling the `:latest` tag would give me the one from 28th Jan, still trying to figure this one out...

**Comment by InsaneGriever** [comment]
Strange. The date of image is 28th Jan. 
Thank you.

**Comment by lolouk44** [comment]
Cool. Closing then :)

**Comment by lolouk44** [comment]
Do me a favour if you can, try and pull again using the `:latest` tag, Think I've fixed the manifest...

**Comment by InsaneGriever** [comment]
I'm already pull with the `:amd64` tag and got last image.
Yes, `:latest` tag pulls image from 3rd Feb.

**Comment by lolouk44** [comment]
Thanks mate
