### ISSUE TITLE
thanks but some data dont show

### ISSUE THREAD

**Issue by guyyar89** [lolouk44/xiaomi_mi_scale#9]
why i cant see this data?
![image](https://user-images.githubusercontent.com/43018733/81090105-e81c5200-8f05-11ea-95c7-584b068ca6a9.png)

**Comment by lolouk44** [comment]
erm I don't know. Why does it rain today?
Sorry, but you need to give me a bit more if you need me to look into this.
Share your scale model, your docker-compose config, how you've set it up in HA, etc...

**Comment by guyyar89** [comment]
lol ok sorry:
![image](https://user-images.githubusercontent.com/43018733/81090841-00d93780-8f07-11ea-9a0b-3cfb644af515.png)
![image](https://user-images.githubusercontent.com/43018733/81090893-177f8e80-8f07-11ea-9407-554a9712ca11.png)

**Comment by lolouk44** [comment]
Which scale you have?

**Comment by guyyar89** [comment]
> Which scale you have?

Xiaomi Mi Body Composition Scale 2

**Comment by guyyar89** [comment]
work perfect
